### ISSUE TITLE
find excercises

### ISSUE THREAD

**Issue by verenaisele** [verenaisele/Capstone-Project#2]
**STORY**
As a stressed digital worker, I want to do some excercises so that I can improve my overall wellbeing.

**Description**
To be able to do an excercise we need a source for different excercises for typical digital worker issues, with description and pictures.

**Acceptance Criteria**

- [x] Information for excercises for in a table containig description and images
- [x] Folder with images

Body parts to search infos for:

1. Eyes
2. Neck

**TASKS**

- [x] Use eye excercises from stress workshop from PDF (PW: RE012021)
[Relaxed Eyes_Handout_Neue Fische Januar.pdf](https://github.com/verenaisele/Capstone-Project/files/6124873/Relaxed.Eyes_Handout_Neue.Fische.Januar.pdf)

- [x] Ask trainer from workshop if it is ok to use the data
- [x] Search excercises and images for eye pain
- [x] Search excercises and images for neck pain
- [x] Create table containing the information with these details:

<img width="266" alt="Screenshot 2021-03-11 at 17 57 26" src="https://user-images.githubusercontent.com/77627438/110824656-8b12ca80-8293-11eb-820f-0c5298b298d2.png">

**Complexity**
L
