### ISSUE TITLE
Create new database

### ISSUE THREAD

**Issue by verenaisele** [verenaisele/Capstone-Project#3]
**STORY**
As a stressed digital worker, I want to do some excercises so that I can improve my overall wellbeing.

**Description**
To be able to do an excercise we need a source for different excercises for typical digital worker issues, with description and pictures.

**Acceptance Criteria**

- [x] API with excercises for office workers containing text and images

**TASKS**

- [x] setup a new API
- [x] setup a backend
- [x] create datastructure for database based on modell

<img width="266" alt="Screenshot 2021-03-11 at 17 57 26" src="https://user-images.githubusercontent.com/77627438/110824656-8b12ca80-8293-11eb-820f-0c5298b298d2.png">

- [x] fill database in MongoDB with information from issue "Find excercise" by using POSTMAN

**Complexity**
L
