### ISSUE TITLE
Find more excercises for database

### ISSUE THREAD

**Issue by verenaisele** [verenaisele/Capstone-Project#7]
**STORY**
As a stressed digital worker, I want to do some excercises so that I can improve my overall wellbeing.

**Description**
To be able to do an excercise we need a source for different excercises for typical digital worker issues, with description and pictures.

**Acceptance Criteria**

- [ ] Information for excercises for in a table containig description and images
- [ ] Folder with images

Body parts to search infos for:

3. Back
4. Shoulders
5. Wrists
6. Headache
7. Stress

**TASKS**

- [ ] Search excercises and images for back pain
- [ ] Search excercises and images for shoulder pain
- [ ] Search excercises and images for wrists
- [ ] Search excercises and images for headache
- [ ] Search excercises and tips to relief overall stress
- [ ] Create (or use existing) table containing the information with these details:

<img width="266" alt="Screenshot 2021-03-11 at 17 57 26" src="https://user-im
